<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <!-- Parent -->
  <parent>
    <groupId>org.jboss</groupId>
    <artifactId>jboss-parent</artifactId>
    <version>53</version>
    <relativePath />
  </parent>

  <!-- Model Version -->
  <modelVersion>4.0.0</modelVersion>

  <!-- Artifact Configuration -->
  <groupId>org.jboss.arquillian.container</groupId>
  <artifactId>arquillian-parent-jetty</artifactId>
  <version>3.0.0.Final-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Arquillian Container Parent Jetty</name>
  <description>Jetty Container integrations for the Arquillian Project</description>
  <url>https://github.com/arquillian/arquillian-container-jetty</url>

  <inceptionYear>2009</inceptionYear>
  <organization>
    <name>Arquillian Community</name>
    <url>https://arquillian.org</url>
  </organization>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <scm>
    <connection>scm:git:https://github.com/arquillian/arquillian-container-jetty.git</connection>
    <developerConnection>scm:git:git@github.com:arquillian/arquillian-container-jetty.git</developerConnection>
    <url>https://github.com/arquillian/arquillian-container-jetty</url>
    <tag>HEAD</tag>
  </scm>

  <issueManagement>
    <system>GitHub Issues</system>
    <url>https://github.com/arquillian/arquillian-container-jetty/issues</url>
  </issueManagement>

  <ciManagement>
    <system>GitHub Actions</system>
    <url>https://github.com/arquillian/arquillian-container-jetty/actions</url>
  </ciManagement>

  <developers>
    <developer>
      <id>arquillian.org</id>
      <name>Arquillian Community</name>
      <organization>arquillian.org</organization>
      <organizationUrl>https://arquillian.org</organizationUrl>
    </developer>
  </developers>

  <!-- Properties -->
  <properties>

    <!-- Versioning -->
    <version.arquillian_core>1.10.2.Final</version.arquillian_core>
    <version.arquillian.enricher>10.0.0.Final</version.arquillian.enricher>
    <version.arquillian.protocol>10.0.0.Final</version.arquillian.protocol>

    <version.shrinkwrap>3.3.4</version.shrinkwrap>

    <version.h2>2.3.232</version.h2>
    <version.slf4j>2.0.19</version.slf4j>

    <!-- override from parent -->
    <jdk.min.version>17</jdk.min.version>

    <jetty12.version>12.0.25</jetty12.version>
    <jetty12.1.version>12.1.0</jetty12.1.version>

    <!-- maven-release-plugin configuration -->
    <releaseProfiles>central-release</releaseProfiles>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.junit</groupId>
        <artifactId>junit-bom</artifactId>
        <version>6.0.3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.jboss.shrinkwrap.resolver</groupId>
        <artifactId>shrinkwrap-resolver-bom</artifactId>
        <version>${version.shrinkwrap}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>
      <dependency>
        <groupId>org.jboss.arquillian</groupId>
        <artifactId>arquillian-bom</artifactId>
        <version>${version.arquillian_core}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.jboss.arquillian</groupId>
        <artifactId>arquillian-build</artifactId>
        <version>${version.arquillian_core}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.jboss.arquillian.protocol</groupId>
        <artifactId>arquillian-protocol-servlet-jakarta</artifactId>
        <version>${version.arquillian.protocol}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.arquillian.testenricher</groupId>
        <artifactId>arquillian-testenricher-cdi-jakarta</artifactId>
        <version>${version.arquillian.enricher}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.arquillian.testenricher</groupId>
        <artifactId>arquillian-testenricher-resource-jakarta</artifactId>
        <version>${version.arquillian.enricher}</version>
      </dependency>
      <dependency>
        <groupId>com.h2database</groupId>
        <artifactId>h2</artifactId>
        <version>${version.h2}</version>
        <scope>test</scope>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${version.slf4j}</version>
      </dependency>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>${version.slf4j}</version>
      </dependency>
      <dependency>
        <groupId>org.hamcrest</groupId>
        <artifactId>hamcrest</artifactId>
        <version>3.0</version>
      </dependency>
      <dependency>
        <groupId>jakarta.annotation</groupId>
        <artifactId>jakarta.annotation-api</artifactId>
        <version>2.1.1</version>
      </dependency>
      <dependency>
        <groupId>org.codehaus.plexus</groupId>
        <artifactId>plexus-utils</artifactId>
        <version>4.0.3</version>
      </dependency>
      <dependency>
        <groupId>org.codehaus.plexus</groupId>
        <artifactId>plexus-xml</artifactId>
        <version>4.0.4</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.3</version>
        <configuration>
          <trimStackTrace>false</trimStackTrace>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>build-server</id>
      <build>
        <plugins>
          <!--
              surefire default forks the JVM for testing, so we need to pass on the maven.repo.local variable so the MavenResovler used in
              the test cases can read from the same local repo.
           -->
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <systemProperties>
                <maven.repo.local>${maven.repo.local}</maven.repo.local>
              </systemProperties>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <modules>
    <module>jetty-embedded-12-1-ee11</module>
    <module>jetty-embedded-12-ee10</module>
    <module>jetty-embedded-12-ee9</module>
    <module>jetty-common</module>
  </modules>

</project>

